### ISSUE TITLE
sys.version should not be used for version checks

### ISSUE THREAD

**Issue by svisser** [regebro/supporting-python-3#9]
The string `sys.version` should not be used for version checks as there is no guarantee across implementations that the version number is at the beginning of the string. Instead `sys.version_info` should be used which is a tuple of integers.

**Comment by regebro** [comment]
There no guarantees about anything here in life. However, people in general seem to prefer version_info, so why not?

**Comment by svisser** [comment]
The docs are quite clear about this, it's not really about personal preferences.
